config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  root 'timelines#index'
  devise_for :users

  resources :likes

  resources :timelines , shallow: true do
    collection do
      post 'filter_by_user'
    end
  end
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :timeline
  
  validates :user_id, :uniqueness => {:scope => :timeline_id}
  
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  
  has_many :replies, class_name: 'Timeline', foreign_key: 'reply_id', dependent: :destroy
  validates :message, presence: true, allow_blank: false, length: { in: 1..150 }      
    
  scope :user_filter, -> user_id do
    where(user_id: user_id) if user_id. present?    
  end
    
  scope :not_reply, -> do
    #返信でないデータ取得
    where(reply_id: nil)
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :timelines
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  mount_uploader :thumbnail, UserThumbnailUploader
  
  validates :name, presence: true
  validates :agreement, presence: true, acceptance: {accept: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :thumbnail, :agreement])
  end
  
  #すべてのいいねのカウントをする
  def count_likes
    likes = Like.all
    likes.group('timeline_id').count
  end
  #１つの投稿へのいいねのカウントをする
  def count_like
    count = Like.where(timeline_id: @timeline_id).count
    if count.nil?
      return 0
    else
      return count
    end
  end
  

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  helper_method :count_like
  
  def create
    like_by = current_user
    @timeline_id = like_params["timeline_id"]
    like = Like.new(user_id: like_by.id, timeline_id: @timeline_id)
    like.save!
    render json: {new_count: count_like}
  end
  
  private
  def like_params
    params.require(:like).permit(:timeline_id)
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def index
    @input_message = Timeline.new
    #メッセージ入力
    @input_message = params[:id] ? Timeline.find(params[:id]) : Timeline.new
    #タイムライン取得
    @timeline = Timeline.includes(:user).not_reply.user_filter(params[:filter_user_id]).order('updated_at DESC')
    #ユーザ一覧取得
    @users = User.all
    @like = Like.new

    if params[:reply_id]
      @reply_timeline = Timeline.find(params[:reply_id])
    end
  end
  
  def create
    timeline = Timeline.new
    timeline.attributes = timeline_params
    timeline.user_id = current_user.id
    @like = Like.new
    if timeline.valid?
      timeline.save!
      respond_to do |format|
        format.html do
          redirect_to action: :index
        end
        format.json do
          html = render_to_string partial: 'timelines/timeline', layout: false, formats: :html, locals: { one_timeline: timeline }
          render json: {timeline: html}
        end
      end
    else
      respond_to do |format|
        format.html do
          flash[:alert] = timeline.errors.full_messages
          redirect_to action: :index
        end
        format.json do
          render json: { error_message: timeline.errors.full_messages }
        end
      end
    end
  end
  
  def update
    timeline = Timeline.find(params[:id])
    timeline.attributes = timeline_params
    if timeline.valid?
      timeline.save!
    else 
      flash[:alert] = timeline.errors.full_messages
    end
    redirect_to action: :index
  end
  
  def destroy
    timeline = Timeline.find(params[:id])
    timeline.destroy
    redirect_to action: :index
  end
  
  def filter_by_user
    if params[:filter_user_id].present?
      redirect_to action: :index, filter_user_id: params[:filter_user_id]
    else
      redirect_to action: :index
    end
  end
  
  private 
  def timeline_params
    params.require(:timeline).permit(:message, :reply_id)
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
  
  #自分の投稿か判定する
  def mypost?(timeline)
    timeline.user.id == current_user.id
  end
  
  #すでにいいねした投稿か判断する
  def already_like?(timeline)
    Like.select('user_id').where(timeline_id: timeline.id).find_by(user_id: current_user.id).present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>ElitesMessenger</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
    <div class="logout_wrapper">
      <%= link_to t('devise.basic.log_out'), destroy_user_session_path, method: :delete %>
    </div>
  <% end %>
  <p class="notice"><%= notice %></p>
  <%= yield %>

</body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/timelines/_timeline.html.erb
<% 
  #is_replyの変数を設定
  is_reply = false if is_reply.nil?
%>

<div class="per <%= 'mine' if mypost?(one_timeline) %> <%= 'reply' if is_reply %> clearfix">
  <p class="icon">
    <% if one_timeline.user.thumbnail? %>
      <%= image_tag one_timeline.user.thumbnail.url %>
    <% else %>
      NO IMAGE
    <% end %>
  </p>
  <%= simple_format one_timeline.message, class: 'message' %>
  <% if mypost?(one_timeline) %>
    <div class="operation">
      <%= link_to root_path(id: one_timeline.id, message: one_timeline.message) do %>
        <%= button_tag t('userdef.edit'), class: 'btn btn-info float-right' %>
      <% end %>
      <%= button_to t('userdef.del'), timeline_path(one_timeline), method: :delete, class: 'btn btn-danger', data: {confirm: '削除しますか？'} %>
    </div>
  <% else %>
    <%= link_to root_path(reply_id: one_timeline.id) do %>
      <%= button_tag t('userdef.Re'), class: 'btn btn-info' %>
    <% end %>
  <% end %>
  <hr>
  <span class: "like_count">
    <%= t('userdef.like') %>：
    <span class: "js-like_count">
      <% if one_timeline.likes.count.nil? %>
        0
      <% else %>
        <%= one_timeline.likes.count %>
      <% end %>
    </span>
  </span>
  <% if not mypost?(one_timeline) %>
    <% if not already_like?(one_timeline) %>
      <%= form_for @like, url:likes_path, remote: true, html: {class: 'like_form'}, authenticity_token: true do |f| %>
        <%= f.hidden_field :timeline_id, value: one_timeline.id %>
        <%= f.submit t('userdef.like'), class: 'btn btn-success js-like' %>
      <% end %>
    <% end %>
  <% end %>
</div>
<% one_timeline.replies.each do |r| %>
  <%= render 'timelines/timeline', one_timeline: r, is_reply: true %>
<% end %>

app/views/timelines/index.html.erb
<div class="wrapper timeline_wrapper">
    <div class="input">
    <%= form_for @input_message, remote: true, html: {class: 'input_message_form'}, format: :json, authenticity_token: true do |f| %>
      <div class="form-group">
        <%= f.label :message %>
        <% if @input_message.persisted? %>
          編集中
        <% elsif @reply_timeline %>
          <%= @reply_timeline.user.name %>の「<%= truncate(@reply_timeline.message, length: 7) %>」に返信
        <% end %>
        <br />
        <%= f.text_area :message, class: 'form-control', rows: 3 %>
      </div>
    
      <div class="actions clearfix">
        <div class="alert">
          <% if flash[:alert] %>
            <% flash[:alert].each do |message| %>
              <p class="alert"><%= message %></p>
            <% end %>
          <% end %>
        </div>
        <div class="post">
          <% if @input_message.persisted? || @reply_timeline %>
            <%= link_to t('userdef.cancel'), root_path, class: 'btn btn-default' %>
          <% end %>
          <%= f.submit t('userdef.post'), class: 'btn btn-primary post' %>
          <%= f.submit t('userdef.ajaxPost'), class: 'btn btn-primary ajaxpost' %>
        </div>
      </div>
      <%= f.hidden_field :reply_id, value: @reply_timeline.id if @reply_timeline %>
    <% end %>
  </div>
  
  <div class="user_filter">
    <%= form_tag filter_by_user_timelines_path do |f| %>
      <div class="form-group">
        <label>ユーザフィルター</label><br />
        <%= select_tag :filter_user_id, options_for_select(@users.map { |m| [m.name, m.id]}, params[:filter_user_id]), prompt: 'フィルターなし', class: 'form-control' %>        
      </div>
      <div class="actions">
        <%= submit_tag t('userdef.apply'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  
  <div class="timeline">
    <% @timeline.each do |one_timeline| %>
      <%= render 'timelines/timeline' , one_timeline: one_timeline, like: @like %>
    <% end %>
  </div>
</div>